ToDoIdentity/Models/Entities/Performer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoIdentity.Extensions;
using ToDoIdentity.Models.Attributes;

namespace ToDoIdentity.Models
{
    public class Performer
    {
        ///<summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        ///<summary>
        /// Имя Исполнителя
        /// </summary> 
        [Required]
        [Display(Name = "Исполнитель", Order = 1)]
        public string Name { get; set; }

        /// <summary>
        /// Фото Исполнителя
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual PerformerImage PerformerImage { get; set; }

        [Display(Name = "Фото исполнителя", Order = 6)]
        [NotMapped]
        public HttpPostedFileBase PerformerImageFile { get; set; }




        /// <summary>
        /// Пол
        /// </summary> 
        [ScaffoldColumn(false)]
        public Sex Sex { get; set; }

        [Display(Name = "Пол", Order = 2)]
        [UIHint("DropDownList")]
        [TargetProperty("Sex")]
        [NotMapped]
        public IEnumerable<SelectListItem> SexDictionary
        {
            get
            {
                var dictionary = new List<SelectListItem>();

                foreach (Sex type in Enum.GetValues(typeof(Sex)))
                {
                    dictionary.Add(new SelectListItem
                    {
                        Value = ((int)type).ToString(),
                        Text = type.GetDisplayValue(),
                        Selected = type == Sex
                    });
                }

                return dictionary;
            }
        }


        ///<summary>
        /// Список предметов, которые ведет преподаватель
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

ToDoIdentity/Controllers/PerformersController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using ToDoIdentity.Extensions;
using ToDoIdentity.Models;

namespace ToDoIdentity.Controllers
{
    [Authorize]
    public class PerformersController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new ToDoContext();
            var teachers = db.Performers.ToList();

            return View(teachers);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var teacher = new Performer();
            return View(teacher);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(Performer model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new ToDoContext();


            if (model.PerformerImageFile != null)
            {
                var data = new byte[model.PerformerImageFile.ContentLength];
                model.PerformerImageFile.InputStream.Read(data, 0, model.PerformerImageFile.ContentLength);

                model.PerformerImage = new PerformerImage()
                {
                    Guid = Guid.NewGuid(),
                    DateChanged = DateTime.Now,
                    Data = data,
                    ContentType = model.PerformerImageFile.ContentType,
                    FileName = model.PerformerImageFile.FileName
                };
            }
            db.Performers.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Performers/Index");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            var db = new ToDoContext();
            var teacher = db.Performers.FirstOrDefault(x => x.Id == id);
            if (teacher == null)
                return RedirectPermanent("/Performers/Index");

            db.Performers.Remove(teacher);
            db.SaveChanges();

            return RedirectPermanent("/Performers/Index");
        }


        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            var db = new ToDoContext();
            var teacher = db.Performers.FirstOrDefault(x => x.Id == id);
            if (teacher == null)
                return RedirectPermanent("/Performers/Index");

            return View(teacher);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Performer model)
        {
            var db = new ToDoContext();
            var teacher = db.Performers.FirstOrDefault(x => x.Id == model.Id);
            if (teacher == null)
                ModelState.AddModelError("Id", "Преподаватель не найден");

            if (!ModelState.IsValid)
                return View(model);

            MappingPerformer(model, teacher, db);

            db.Entry(teacher).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Performers/Index");
        }

        private void MappingPerformer(Performer sourse, Performer destination, ToDoContext db)
        {
            destination.Name = sourse.Name;
            destination.Sex = sourse.Sex;

            if (sourse.PerformerImageFile != null)
            {
                var image = db.PerformerImages.FirstOrDefault(x => x.Id == sourse.Id);
                if (image != null)
                    db.PerformerImages.Remove(image);

                var data = new byte[sourse.PerformerImageFile.ContentLength];
                sourse.PerformerImageFile.InputStream.Read(data, 0, sourse.PerformerImageFile.ContentLength);

                destination.PerformerImage = new PerformerImage()
                {
                    Guid = Guid.NewGuid(),
                    DateChanged = DateTime.Now,
                    Data = data,
                    ContentType = sourse.PerformerImageFile.ContentType,
                    FileName = sourse.PerformerImageFile.FileName
                };
            }
        }
        [HttpGet]
        public ActionResult GetImage(int id)
        {
            var db = new ToDoContext();
            var image = db.PerformerImages.FirstOrDefault(x => x.Id == id);
            if (image == null)
            {
                FileStream fs = System.IO.File.OpenRead(Server.MapPath(@"~/Content/Images/not-foto.png"));
                byte[] fileData = new byte[fs.Length];
                fs.Read(fileData, 0, (int)fs.Length);
                fs.Close();

                return File(new MemoryStream(fileData), "image/jpeg");
            }

            return File(new MemoryStream(image.Data), image.ContentType);
        }

        [HttpGet]
        public ActionResult GetXlsx()
        {
            var db = new ToDoContext();
            var xlsx = db.Performers.ToXlsx();

            return File(xlsx.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Performers.xlsx");
        }
    }
}

ToDoIdentity/Views/Performers/Create.cshtml
@using ToDoIdentity.Models
@model Performer

<h2>Исполнитель</h2>
<br />
<fieldset>
    <legend><h3>Пожалуйста, заполните необходимые поля</h3></legend>
    @using (Html.BeginForm("Create", "Performers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Performers", null, new { @class = "btn btn-danger" })
    }
</fieldset>

ToDoIdentity/Views/Performers/Edit.cshtml
@using ToDoIdentity.Models
@model Performer

<h2>Исполнитель</h2>
<br />
<legend><h3>Пожалуйста, заполните необходимые поля</h3></legend>

@using (Html.BeginForm("Edit", "Performers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    @Html.EditorForModel()

    <input type="submit" value="Сохранить" class="btn btn-secondary" />
    @Html.ActionLink("Отменить", "Index", "Performers", null, new { @class = "btn btn-danger" })
}

ToDoIdentity/Views/Performers/Index.cshtml
@using ToDoIdentity.Models
@using ToDoIdentity.Extensions
@model List<Performer>

@{
    string controllerName = "Performers";
}
<br />
<h1><b>Исполнители</b></h1>

@if (User.IsInRole("Administrator"))
{
<div class="btn-create" style="display: flex;">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
    @Html.ActionLink("Excel", "GetXlsx", controllerName, null, new { @class = "btn btn-outline-dark", style = "margin: 0px 15px 0px 15px;" })
</div>
    <br />
}

    <table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
        <thead>
            <tr>
                <th>
                    Исполнитель
                </th>
                <th>
                    Пол
                </th>
                <th>
                    Фото Исполнителя
                </th>
                @if (User.IsInRole("Administrator"))
                {
                    <th>
                        Действия
                    </th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var performer in Model)
            {
                <tr>
                    <td>
                        @performer.Name
                    </td>
                    <td>
                        @performer.Sex.GetDisplayValue()
                    </td>
                    <td>
                        <img src="/Performers/GetImage/@performer.Id" style="max-width: 100px; max-height: 200px;" />
                    </td>
                    @if (User.IsInRole("Administrator"))
                    {
                        <td>
                            <div class="btn-group mb-3, vertical-align:middle align-middle">
                                <a href="/@controllerName/Edit/@performer.Id" class="btn btn-outline-dark">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                    </svg>
                                </a>
                                <a href="/@controllerName/Delete/@performer.Id" class="btn btn-outline-dark">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                        <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                                    </svg>
                                </a>
                            </div>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>